services:
  db:
    image: postgres:16-alpine
    container_name: fastapidelivery_db
    restart: always
    environment:
      POSTGRES_USER: fastapidelivery_user
      POSTGRES_PASSWORD: fastapidelivery
      POSTGRES_DB: fastapidelivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foodmeal_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapidelivery_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./media:/app/media
    networks:
      - foodmeal_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: foodmeal_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - foodmeal_network
    restart: unless-stopped

networks:
  foodmeal_network:
    driver: bridge

volumes:
  postgres_data:
